name: CI-on-prerelease

on: 
    release:
        types: [prereleased]

jobs:
  update_version_info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Version info
      run: ./src/prerelease.sh
    - name: switch from https to ssh
      run: |
          git config --global user.email "michael@sparkgrills.com"
          git config --global user.name "Michael Chiasson"
          git fetch
    - name: get branch name?
      run: |
          echo "github.event.author: ${{ github.event.author }}"
          echo "github.event.target_commitish: ${{ github.event.target_commitish }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.payload: ${{ github.payload }}"
          echo "GITHUB_REF: $GITHUB_REF"

