name: CI-on-release

on: [release, workflow_dispatch]

jobs:
  update_version_info:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Version info
      run: ./src/release.sh
    - name: switch from https to ssh
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: stage
      run: git add src/config/sdk_config.h
    - name: commit
      run: git commit -m "post Release version info update"
    - name: push
      run: git push origin HEAD:master
